// Velite types — auto-generated by Velite, but we need the type declarations here
// This file tells TypeScript where to find Velite's generated content

declare module "@/.velite" {
    export interface Post {
        title: string;
        slug: string;
        dek: string;
        excerpt: string;
        description: string;
        date: string;
        updated?: string;
        author: string;
        category: string;
        tags: string[];
        image: string;
        imageAlt: string;
        draft: boolean;
        featured: boolean;
        breaking: boolean;
        seoTitle?: string;
        seoDescription?: string;
        canonicalUrl?: string;
        ogImage?: string;
        keywords: string[];
        body: string;
        metadata: {
            readingTime: number;
            wordCount: number;
        };
    }

    export interface Page {
        title: string;
        slug: string;
        description: string;
        seoTitle?: string;
        seoDescription?: string;
        image?: string;
        body: string;
    }

    export const posts: Post[];
    export const pages: Page[];
}
